FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=senhaSuperSegura
ENV DB_TYPE=sqlite
ENV N8N_HOST=n8n-k3xb.onrender.com
ENV N8N_PORT=10000
EXPOSE 10000
